[plugins]
userdev = { id = "io.papermc.paperweight.userdev", version = "1.5.12" }
bukkit-convention = { id = "xyz.jpenilla.resource-factory-bukkit-convention", version = "1.0.0" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
run-paper = { id = "xyz.jpenilla.run-paper", version = "2.2.3" }

[versions]
bundle = "1.20.4-R0.1-SNAPSHOT"

[libraries]
placeholder-api = { group = "me.clip", name = "placeholderapi", version = "2.11.5" }

vital = { group = "com.ryderbelserion.vital", name = "Vital", version = "1.0-snapshot" }

triumph-cmds = { group = "dev.triumphteam", name = "triumph-cmd-bukkit", version = "2.0.0-SNAPSHOT" }
triumph-gui = { group = "dev.triumphteam", name = "triumph-gui", version = "3.1.7" }

vault = { group = "com.github.MilkBowl", name = "VaultAPI", version = "1.7.1" }
metrics = { group = "org.bstats", name = "bstats-bukkit", version = "3.0.2" }
config-me = { group = "ch.jalu", name = "configme", version = "1.4.1" }

[bundles]
triumph = ["triumph-cmds", "triumph-gui"]